on:
  workflow_dispatch:
    inputs:
      AVD_VERSION:
        description: "Version of AVD to test"
        required: True
        default: "4.8"
        type: string

jobs:
  avd-build:
    runs-on: ubuntu-latest
    container:
      image: git.as73.inetsix.net/docker/pylab-runner:node
    steps:
      - uses: actions/checkout@v4
      - name: Update requirements
        run: |
          pip install --upgrade -r requirements.txt
          ansible-galaxy collection install --force -r collections.yml
          ansible-galaxy collection install --force "arista.avd==${{AVD_VERSION}}"
      - name: Run ANSIBLE AVD to BUILD
        run: |
          ansible-playbook playbooks/atd-fabric-deploy.yml --diff --tags build
      - name: Upload AVD outputs
        uses: https://code.forgejo.org/forgejo/upload-artifact@v4
        with:
          name: avd-configuration
          path: "**inventory/*"
